matches:
  - trigger: "/lvdk"
    replace: "Lemstra Van der Korst"
  
  # Redigeer tekst
  - trigger: "/spelling"
    replace: "Controleer spelling, grammatica, opbouw, logica en bondigheid van onderstaande tekst. Vervang waar nodig. Behoud de originele taal. Geef de volledige verbeterde tekst terug met links het origineel en rechts de verbeterde tekst. Als er geen verbeteringen zijn dan kan je gewoon aangegeven dat de tekst daar niet is verbeterd. Je hoeft de opdracht niet te herhalen en hoeft ook geen inleidend tekstje te geven voor de verbeterde tekst. Tekst: "
  
  # Met vriendelijke groet
  - trigger: "/mvg"
    replace: "Met vriendelijke groet,"
  
  # Best regards
  - trigger: "/br"
    replace: "Best regards,"
    
  # Plaatje genereren
  - trigger: "/plaatje"
    replace: "Maak een [stijl van illustratie, bijv. realistische, cartoonachtige, abstracte, digitale schilderij] illustratie van [hoofdonderwerp of scène], waarbij de volgende elementen zichtbaar zijn: [beschrijf omgeving, personages, objecten, kleuren, sfeer]. De setting is [locatie en/of tijd van de dag/seizoen], met [eventuele specifieke details zoals kleding, houding, perspectief, lichtinval]. Gebruik een beeldverhouding van [bijv. 16:9 of vierkant] en geef prioriteit aan [bijv. sfeer, detaillering, compositie, kleurgebruik]."
    
  # Doorzoek
  - trigger: "/doorzoek"
    markdown: Doorzoek uitsluitend het aangehechte PDF-bestand en geef een overzicht van alle relevante passages waarin [**beschrijf hier de specifieke juridische kwestie, term, clausule of gebeurtenis**] wordt behandeld. Vermeld per gevonden resultaat:  - Het paginanummer (en indien beschikbaar het randnummer);\n - Een korte samenvatting van de relevante inhoud;\n - Indien van toepassing: een letterlijke citaat van de relevante passage.\n\nBeperk je uitsluitend tot informatie uit het PDF-bestand en geef geen aanvullingen uit andere bronnen."